<h2>CARRINHO</h2>
<div class="row">
    <div class="col-md-12">
        <?php
        //var_dump($this->produtos);exit;
        if (!is_array($this->produtos) && !empty($this->produtos)) :
            echo "<h2>Produto não encontrado :(</h2></div></div>";
         else :

               foreach ($this->produtos as $key => $value) :?>
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><?php echo $value['nome'];?></h3>
                </div>
                <div class="panel-body">
                    <div class="col-md-5">
                        <img class="img-thumbnai img-responsive" style="height: 120px;width: 120px;" src="/img/produto/<?php echo $value['imagem'] ?>">
                    </div>
                    <div class="col-md-7">
                        <p>
                            <?php echo $value['descricao']?>
                        </p>
                        <p><b>
                            <?php echo 'R$ '.number_format($value['preco'],2,',','.');?>
                        </b></p>

                    </div>
                    <div class="row col-md-12 pull-right">
                        <a class="btn btn-danger" href="/application/removeCarrinho?id=<?php echo $value['id']?>">-</a>
                        <b class="text-center"><?php echo $value['quantidade']; ?></b>
                        <a class="btn btn-success" href="/application/addCarrinho?id=<?php echo $value['id']?>">+</a>

                    </div>
                </div>
            </div>
        </div>
    <?php endforeach;?>

    </div>
    <div class="jumbotron col-md-12">
        <h3><span class="zf-green">Dados de acesso</span></h3>
        <h4 class="zf-green">
            Login
        </h4>
        <form action="cadastro" method="post">
      <div class="form-group">
        <?php echo $this->formLabel($this->form->get('email')); ?>
        <?php echo $this->formElement($this->form->get('email')); ?>
      </div>
      <div class="form-group">
        <?php echo $this->formLabel($this->form->get('senha')); ?>
        <?php echo $this->formElement($this->form->get('senha')); ?>
      </div>

        <!-- /.col -->
        <div class="form-group">
          <?php echo $this->formElement($this->form->get('submit')); ?>
        </div>
        <!-- /.col -->

    </form>
    <br>
        <h4 class="zf-green">
            Cadastro
        </h4>


    </div>
</div>
<?php endif; ?>