<div class="jumbotron">
    <h1>BEM VINDO(A) A <span class="zf-green">LOJA SIMPLES</span></h1>

    <p>
        Aqui você pode analisar o desempenho do candidato DOUGLAS LEONARDO! Não esqueça de levar em consideração que este teste foi feito em apenas algumas horas. Espero ter me saído bem :)
    </p>
</div>
<div class="row">
    <div class="col-md-6">
    <p><b><h4>Pesquisar Produtos</h4><b></p>
        <form class="form form-group" method="post" action="/application/busca">
            <label for="pesq-nome">Nome</label>
            <input type="text" class="form-control" name="pesq-nome" id="pesq-nome" placeholder="Ex. Mesa"/>
            <label for="pesq-categoria">Categoria</label>
            <?php
            if (is_array($this->categorias)) :
            ?>
            <select name="pesq-categoria" class="form-control" id="pesq-categoria">
                <option value="">Selecione uma opção</option>
            <?php foreach ($this->categorias as $key => $value):?>
                <option value="<?php echo $value['nome']?>"><?php echo $value['nome']?></option>

            <?php endforeach;?>
            </select>
            <?php endif;?>
            <button type="submit" id="btn-submit" class="btn btn-success pull-right" style="margin-top: 15px;margin-bottom: 30px;">Pesquisar &raquo;</button>
        </form>
    </div>
</div>

<div class="row" id="lk-lista-produtos">
    <?php
    if (!is_array($this->produtos) || empty($this->produtos)) {
        echo "<h2>Produto não encontrado :(</h2>";
    }

    foreach ($this->produtos as $key => $value)
    :?>
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><?php echo $value['nome'];?></h3>
                </div>
                <div class="panel-body">
                    <div class="col-md-5">
                        <img class="img-thumbnai img-responsive" src="/img/produto/<?php echo $value['imagem'] ?>">
                    </div>
                    <div class="col-md-7">
                        <p>
                            <?php echo $value['descricao']?>
                        </p>
                        <p><b>
                            <?php echo 'R$ '.number_format($value['preco'],2,',','.');?>
                        </b></p>

                    </div>

                    <p><a class="btn btn-success pull-right" href="/application/detalhe?id=<?php echo $value['id']?>">Comprar &raquo;</a></p>
                </div>
            </div>
        </div>
    <?php endforeach;?>
</div>
<script type="text/javascript">
    //VALIDACAO SIMPLES DOS CAMPOS DE BUSCA.
    $("#btn-submit").click(function(event) {
        /* Act on the event */
        if($("#pesq-categoria").val() =="" && $("#pesq-nome").val() == "") {
            alert("Selecione uma categoria ou digite um nome para efetuar a busca!");
            return false;
        } else {
            $(".form").submit();
        }
    });

</script>
