<h2 class="zf-green">Pagamento Aprovado!</h2><br>
<div class="row">
    <div class="col-md-12">
        <?php
        if (!is_array($this->pedidos) || !isset($this->pedidos[0]['id'])) :
            echo "<h2>Nenhum pedido encontrado :(</h2></div></div>";
         else :
            foreach ($this->pedidos['itens'] as $k => $itens) : ?>

            <table class="table table-bordered">
            <thead>
              <tr>
                <th>Código Pedido</th>
                <th>Produto</th>
                <th>DETALHE</th>
                <th>Preço unidade</th>
                <th>Quantidade</th>
                <th>Preço Total</th>
              </tr>
            </thead>
            <tbody>
           <?php foreach ($itens as $key => $value) :
                ?>
              <tr>
                <td><?php echo $k?></td>
                <td><?php echo $value['nome']?></td>
                <td><a href="detalhe?id=<?php echo $value['id'];?>" >VER DETALHE DO ITEM</a></td>
                <td><?php echo "R$ ".number_format($value['preco'],2,',','.');?></td>
                <td><?php echo $value['qtd']?></td>
                <td><?php echo "R$ ".number_format(($value['preco'] * $value['qtd']),2,',','.')?></td>
              </tr>

        <?php endforeach;endforeach;?>
        </tbody>
        </table>
        <br>
        <p align="center"><a href="/application/pedidos">VER TODOS OS MEUS PEDIDOS</a></p>
    </div>
</div>
<?php endif; ?>